version: '3.3'

services:    
    service-registry:
        networks:
            - my-net
        build:
            context: service-registry
            args:
                JAR_FILE: target/service-registry-0.0.19-SNAPSHOT.jar
        dns: 10.62.63.16
        env_file:
          - .env
        #volumes:
        #    - "/c/Users/mhonzirek/Downloads/logs:/logs"
#        volumes:
#            - /logs
    config-server:
        networks:
            - my-net
        build:
            context: config-server
            args:
                JAR_FILE: target/config-server-0.0.19-SNAPSHOT.jar
        dns: 10.62.63.16
        depends_on:
            - service-registry
        env_file:
          - .env
        ports:
            - 8888
        #volumes:
        #    - "/c/Users/mhonzirek/Downloads/logs:/logs"
    taco-service:
        networks:
            - my-net
        build:
            context: taco-service
            args:
                JAR_FILE: target/taco-service-0.0.19-SNAPSHOT.jar
        dns: 10.62.63.16
        ports:
            - 8081
            - 8000
#        volumes:
#            - /logs
        #volumes:
        #    - "/c/Users/mhonzirek/Downloads/logs:/logs"
        environment:
            - JAVA_TOOL_OPTIONS=-agentlib:jdwp=transport=dt_socket,address=8000,server=y,suspend=n
        depends_on:
            - service-registry
            - config-server
        #command: ["./wait-for-it.sh", "config-server:8888", "-t", "45", "--", "java", "-Djava.security.egd=file:/dev/./urandom", "-jar", "/app.jar"]
    ingredient-service:
        networks:
            - my-net
        build:
            context: ingredient-service
            args:
                JAR_FILE: target/ingredient-service-0.0.19-SNAPSHOT.jar
        dns: 10.62.63.16
        ports:
            - 8080
            - 8000
        #        volumes:
        #            - /logs
        #env_file:
        #    - .env
        #volumes:
        #    - "/c/Users/mhonzirek/Downloads/logs:/logs"
        environment:
            - JAVA_TOOL_OPTIONS=-agentlib:jdwp=transport=dt_socket,address=8000,server=y,suspend=n
        depends_on:
            - service-registry
            - config-server
        #command: ["./wait-for-it.sh", "config-server:8888", "-t", "45", "--", "java", "-Djava.security.egd=file:/dev/./urandom", "-jar", "/app.jar"]
    ingredient-client:
        networks:
            - my-net
        build:
            context: ingredient-client
            args:
                JAR_FILE: target/ingredient-client-0.0.19-SNAPSHOT.jar
        dns: 10.62.63.16
        ports:
            - 8080
            - 8000
        #        volumes:
        #            - /logs
        #volumes:
        #    - "/c/Users/mhonzirek/Downloads/logs:/logs"
        environment:
            - JAVA_TOOL_OPTIONS=-agentlib:jdwp=transport=dt_socket,address=8000,server=y,suspend=n
        #    - SPRING_PROFILES_ACTIVE=feign
        depends_on:
            - service-registry
            - config-server
        #command: ["./wait-for-it.sh", "config-server:8888", "-t", "45", "--", "java", "-Djava.security.egd=file:/dev/./urandom", "-jar", "/app.jar"]
    proxy-server:
        networks:
            - my-net
        build:
            context: proxy-server
            args:
                JAR_FILE: target/proxy-server-0.0.19-SNAPSHOT.jar
        dns: 10.62.63.16
        ports:
            - 8080
            - 8000
        #        volumes:
        #            - /logs
        #volumes:
        #    - "/c/Users/mhonzirek/Downloads/logs:/logs"
        environment:
            - JAVA_TOOL_OPTIONS=-agentlib:jdwp=transport=dt_socket,address=8000,server=y,suspend=n
        depends_on:
            - service-registry
            - config-server
        command: ["./wait-for-it.sh", "config-server:8888", "-t", "45", "--", "java", "-Djava.security.egd=file:/dev/./urandom", "-jar", "/app.jar"]
    hystrix-dashboard:
        networks:
            - my-net
        build:
            context: hystrix-dashboard
            args:
                JAR_FILE: target/hystrix-dashboard-0.0.19-SNAPSHOT.jar
        dns: 10.62.63.16
        ports:
            - 8080
            - 8000
            - 7979
        #        volumes:
        #            - /logs
        #volumes:
        #    - "/c/Users/mhonzirek/Downloads/logs:/logs"
        environment:
            - JAVA_TOOL_OPTIONS=-agentlib:jdwp=transport=dt_socket,address=8000,server=y,suspend=n
        depends_on:
            - service-registry
            - config-server
        #command: ["./wait-for-it.sh", "config-server:8888", "-t", "45", "--", "java", "-Djava.security.egd=file:/dev/./urandom", "-jar", "/app.jar"]
networks:
    my-net:
